# Generated by Django 5.1.1 on 2024-09-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rarity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='bouquet_type',
            field=models.CharField(choices=[('single', 'Single'), ('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='wrap_color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
